name: cvx
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn
  - jupyter
  - ipykernel
  - plotly
  - pyarrow
  - pip:
    - maturin
    - sentence-transformers
